### ISSUE TITLE
Does it support tailwindUI

### ISSUE THREAD

**Issue by oorestisime** [christianalfoni/stitches#12]
Hey 

awesome new library! I like the direction this is going with integrating with tailwind. I wonder whether it also supports tailwind UI. THe question could be more general like supporting tailwind plugins both those that add utilities and those who add components (i.e https://github.com/tailwindcss/custom-forms )

excited to test this out!

**Comment by christianalfoni** [comment]
Hi @oorestisime and thanks for the feedback 😄 

You should be able to use this library to to build what you see in Tailwind UI, as it is based on the same CSS. Though it would not be a copy/paste operation, as the API is different. Also the plugins hook into their configuration tool I believe, so that would not work.

That said! It would be possible to build like a component library reflecting Tailwind UI where you would consume actual components instead of copy/paste code from their website 😄

**Comment by christianalfoni** [comment]
Please reopen if any more questions 😄
